
import axios from 'axios'
import Head from 'next/head'
import Body from '../components/Body'
import Header from '../components/Header'


export default function Index(props) {
 
  return (
    <div className='max-w-[screen] relative'>
      <Head>
          <title>Blog app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className='max-w-5xl mx-auto'>
        

        <div className='sticky top-0 z-10'>
          <Header/>
        </div>
        
        
        <Body content={props.blogdata}/>
        
      </div>
    </div>
    
  )
}

// export async function getStaticProps(context) {
//   const response = await axios.get('http://localhost:5000')
//   return {
//     props: {
//       blogdata : response.data
//     }, 
//     revalidate: 10,
//   }
// }

export async function getServerSideProps(){
  const response = await axios.get(`${process.env.NEXT_PUBLIC_API_FETCH}`)
  return {
    props: {
      blogdata : response.data
    }, 
  }
}
